name: CodSpeed

on:
  push:
    branches: [ "main" ]
    paths:
      - "pyproject.toml"
      - "uv.lock"
      - "src/**"
      - "tests/**"
      - ".github/workflows/codspeed.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "pyproject.toml"
      - "uv.lock"
      - "src/**"
      - "tests/**"
      - ".github/workflows/codspeed.yml"
  workflow_dispatch:

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          enable-cache: true
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: 3.14
      - name: Install the Project
        run: uv sync --frozen --no-dev --group test
      - name: Run benchmarks
        uses: CodSpeedHQ/action@3194d9a39c4d46684cb44bf7207fc56626aad8fd # v4
        with:
          run: uv run py.test tests/ --codspeed
          mode: simulation
