name: CodSpeed

on:
  push:
    branches: [ "main" ]
    paths:
      - "pyproject.toml"
      - "uv.lock"
      - "src/**"
      - "tests/**"
      - ".github/workflows/codspeed.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "pyproject.toml"
      - "uv.lock"
      - "src/**"
      - "tests/**"
      - ".github/workflows/codspeed.yml"
  workflow_dispatch:

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          enable-cache: true
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version: 3.14
      - name: Install the Project
        run: uv sync --frozen --no-dev --group test
      - name: Run benchmarks
        uses: CodSpeedHQ/action@373d6868929f444bc08d901fd0eb0ad52a8875ea # v5
        with:
          run: uv run py.test tests/ --codspeed
          mode: simulation
