name: CodSpeed

on:
  push:
    branches: [ "main" ]
    paths:
      - "pyproject.toml"
      - "uv.lock"
      - "src/**"
      - "tests/**"
      - ".github/workflows/codspeed.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "pyproject.toml"
      - "uv.lock"
      - "src/**"
      - "tests/**"
      - ".github/workflows/codspeed.yml"
  workflow_dispatch:

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          enable-cache: true
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.14
      - name: Install the Project
        run: uv sync --frozen --no-dev --group test
      - name: Run benchmarks
        uses: CodSpeedHQ/action@v4
        with:
          run: uv run py.test tests/ --codspeed
          mode: simulation
